// 自動產生 — 藥品圖鑑資料（已對抗式驗證，只採 verified-real 欄位）
// 基本/適應症：藥台灣 drugtw 彙整｜外觀標記：食藥署官方外觀｜深度臨床：經驗證之醫院藥品頁
// 刻意不放：健保代號（萃取agent系統性由許可證號臆造）、未經食藥署核實之外觀。POC，版權屬原始來源。
import 'drug_atlas.dart';

final List<DiseaseGroup> drugAtlasGroups = [
  DiseaseGroup('十二指腸潰瘍', [
    DrugFull(
      slug: 'ulcer_lansoprazole', disease: '十二指腸潰瘍',
      chiName: '泰克胃通 口溶錠15毫克',
      enName: 'TAKEPRON OD 15MG TABLETS',
      ingredient: 'LANSOPRAZOLE',
      drugClass: 'PPI（氫離子幫浦抑制劑 / 質子幫浦抑制劑）',
      license: '衛署藥輸字第024272號',
      appearanceMark: '白色圓形（白底散佈橙紅斑點，8mm）',
      appearanceSource: '食藥署',
      indication: '胃潰瘍、十二指腸潰瘍、胃食道逆流性疾病-糜爛性逆流性食道炎之治療、胃食道逆流性疾病之症狀治療。ZOLLINGER-ELLISON症候群、合併抗生素治療與幽門螺旋桿菌(HELICOBACTER PYLORI)相關的消化性潰瘍、治療因NSAID類藥物引起之胃潰瘍。',
      photoAsset: 'assets/drugs/ulcer_lansoprazole.jpg',
      fdaImage: true,
    ),
    DrugFull(
      slug: 'ulcer_pantoprazole', disease: '十二指腸潰瘍',
      chiName: '保衛康治潰樂腸溶膜衣錠40毫克',
      enName: 'PANTOLOC GASTRO-RESISTANT TABLETS 40MG',
      ingredient: 'PANTOPRAZOLE SODIUM SESQUIHYDRATE',
      drugClass: 'PPI（氫離子幫浦阻斷劑 / 質子幫浦抑制劑）',
      license: '衛署藥輸字第022139號',
      appearanceMark: '黃色橢圓形，標記：P40（12mm）',
      appearanceSource: '食藥署',
      indication: '合併二種適當之抗微生物製劑治療與幽門螺旋桿菌相關之消化性潰瘍、胃潰瘍、十二指腸潰瘍、中度及嚴重胃食道逆流性疾病、Zollinger-Ellison Syndrome。',
      photoAsset: 'assets/drugs/ulcer_pantoprazole.jpg',
      fdaImage: true,
    ),
    DrugFull(
      slug: 'ulcer_esomeprazole', disease: '十二指腸潰瘍',
      chiName: '耐適恩錠40公絲',
      enName: 'NEXIUM TABLETS 40MG',
      ingredient: 'ESOMEPRAZOLE MAGNESIUM TRIHYDRATE',
      drugClass: 'PPI（氫離子幫浦抑制劑 / 質子泵抑制劑）',
      license: '衛署藥輸字第023221號',
      indication: '胃食道逆流性疾病-糜爛性逆流性食道炎之治療。-胃食道逆流性疾病之症狀治療。與適當之抗菌劑療法併用，以根除幽門螺旋桿菌，及治療-由幽門螺旋桿菌引發之十二指腸潰瘍。需要持續使用非類固醇抗發炎藥(NSAID)之病患。-NSAID治療相關之胃潰瘍的治療。-Zollinger-Ellison Syndrome(ZES)之治療。預防消化性潰瘍再出血之治療。',
      photoAsset: 'assets/drugs/ulcer_esomeprazole.jpg',
      fdaImage: false,
    ),
    DrugFull(
      slug: 'ulcer_omeprazole', disease: '十二指腸潰瘍',
      chiName: '樂酸克膠囊20公絲',
      enName: 'LOSEC 20MG CAPSULES',
      ingredient: 'OMEPRAZOLE',
      drugClass: 'PPI（質子幫浦抑制劑）',
      license: '衛署藥輸字第017808號',
      indication: '十二指腸潰瘍、胃潰瘍、逆流性食道炎、Ｚ－Ｅ症候群、合併抗生素治療與幽門螺旋桿菌（ＨＥＬＩＣＯＢＡＣＴＥＲ　ＰＹＬＯＲＩ）相關的消化性潰瘍。',
      photoAsset: 'assets/drugs/ulcer_omeprazole.jpg',
      fdaImage: false,
    ),
    DrugFull(
      slug: 'ulcer_sucralfate', disease: '十二指腸潰瘍',
      chiName: '大豐優賜胃錠500公絲(斯克拉非)',
      enName: 'ULSAWE TABLETS 500MG T.F.(SUCRALFATE)',
      ingredient: 'BASIC ALUMINUM SUCROSE SULFATE (SUCRALFATE)',
      drugClass: '胃黏膜保護劑（Sucralfate，硫糖鋁，cytoprotective / 黏膜保護劑）',
      license: '衛署藥製字第029736號',
      appearanceMark: '白色圓形，直線刻痕，標記：TF（12mm）',
      appearanceSource: '食藥署',
      indication: '胃潰瘍、十二指腸潰瘍',
      photoAsset: 'assets/drugs/ulcer_sucralfate.jpg',
      fdaImage: true,
    ),
    DrugFull(
      slug: 'ulcer_amoxicillin', disease: '十二指腸潰瘍',
      chiName: '信東 安謀黴素膠囊500毫克',
      enName: 'AMOXICILLIN CAPSULES 500MG TBC.',
      ingredient: 'AMOXYCILLIN (TRIHYDRATE)',
      drugClass: '盤尼西林類（aminopenicillin）廣效抗生素（ATC J01CA04）',
      license: '衛署藥製字第023239號',
      appearanceMark: '紅色膠囊，標記：ST（22mm）',
      appearanceSource: '食藥署',
      indication: '葡萄球菌、鏈球菌、肺炎雙炎菌、腦膜炎球菌及其他具有感受性細菌引起之感染症',
      sideEffects: '可能有皮疹、噁心、嘔吐、腹瀉等現象。',
      precautions: '1.勿自行停藥。2.口服避孕藥作用受影響。',
      deepSource: 'websrv01.tpech.gov.tw',
      photoAsset: 'assets/drugs/ulcer_amoxicillin.jpg',
      fdaImage: true,
    ),
  ]),
  DiseaseGroup('紅斑性狼瘡', [
    DrugFull(
      slug: 'lupus_hcq', disease: '紅斑性狼瘡',
      chiName: '必賴克瘻膜衣錠200毫克',
      enName: 'PLAQUENIL TABLETS 200MG',
      ingredient: 'HYDROXYCHLOROQUINE SULFATE',
      drugClass: '抗瘧/免疫調節劑（抗風濕 DMARD，hydroxychloroquine）',
      license: '衛署藥輸字第022376號',
      appearanceMark: '白色圓形，標記：HCQ（10mm）',
      appearanceSource: '食藥署',
      indication: '圓盤狀及全身性紅斑性狼瘡、慢性多形日光疹、慢性風濕性關節炎、鐮狀瘧原蟲和間日瘧原蟲引起之瘧疾。',
      photoAsset: 'assets/drugs/lupus_hcq.jpg',
      fdaImage: true,
    ),
    DrugFull(
      slug: 'lupus_hcq2', disease: '紅斑性狼瘡',
      chiName: '健亞 殲瘧膜衣錠200毫克(硫酸羥氯奎寧)',
      enName: 'GENIQUIN FILM COATED TABLETS 200MG (HYDROXYCHLOROQUINE SULFATE)',
      ingredient: 'HYDROXYCHLOROQUINE SULFATE',
      drugClass: '抗瘧/免疫調節（hydroxychloroquine，4-aminoquinoline 抗瘧藥兼疾病修飾抗風濕藥 DMARD）',
      license: '衛署藥製字第042899號',
      appearanceMark: '粉色圓形，標記：GBL（11.1mm）',
      appearanceSource: '食藥署',
      indication: '圓盤狀及全身性紅斑性狼瘡、慢性多形日光疹、慢性風濕性關節鹽、鏈狀瘧原蟲和間日瘧原蟲引起之瘧疾。',
      photoAsset: 'assets/drugs/lupus_hcq2.jpg',
      fdaImage: true,
    ),
    DrugFull(
      slug: 'lupus_prednisolone', disease: '紅斑性狼瘡',
      chiName: '普力多寧錠',
      enName: 'PREDONINE TABLETS',
      ingredient: 'PREDNISOLONE',
      drugClass: '全身性皮質類固醇（Glucocorticoid / 腎上腺皮質類固醇）',
      license: '內衛藥製字第000711號',
      indication: '風濕性疾患、支氣管氣喘、腎炎症候群、過敏性皮膚疾患',
      photoAsset: 'assets/drugs/lupus_prednisolone.jpg',
      fdaImage: false,
    ),
    DrugFull(
      slug: 'lupus_azathioprine', disease: '紅斑性狼瘡',
      chiName: '移護寧50毫克錠',
      enName: 'IMURAN AZATHIOPRINE TABLETS 50MG B.P.',
      ingredient: 'AZATHIOPRINE',
      drugClass: '免疫抑制劑（嘌呤類抗代謝藥 / purine antimetabolite immunosuppressant）',
      license: '衛署藥輸字第009147號',
      indication: '腎臟移植手術防止排斥作用的輔助療法、全身性紅斑狼瘡、重度風濕性關節炎、急慢性白血病',
      dosage: '腎臟移植：成人及兒童口服，移植當日起始 3-5 mg/kg/day，術後維持 1-3 mg/kg/day。類風濕性關節炎：口服起始 1 mg/kg/day，每 4 週增加 0.5 mg/kg/day，最高 2.5 mg/kg/day。',
      sideEffects: '因免疫力下降而增加感染機會，或引起噁心、腹瀉、腸胃不適、不正常出血或瘀血、關節痛、水腫、頻尿等；亦可能出現齒齦增生、骨髓抑制、白血球減少、血小板減少、肝功能異常、皮疹。',
      precautions: '1. 需定期檢查血球及肝功能。2. 警惕骨髓抑制跡象。3. 如與 allopurinol 併用，azathioprine 劑量需減為 ⅓ 至 ¼。屬危險藥品（! 危險藥品）。',
      deepSource: 'csh.com.tw',
      photoAsset: 'assets/drugs/lupus_azathioprine.jpg',
      fdaImage: false,
    ),
    DrugFull(
      slug: 'lupus_mmf', disease: '紅斑性狼瘡',
      chiName: '睦體康180毫克腸衣錠',
      enName: 'MYFORTIC 180MG GASTRO-RESISTANT TABLETS',
      ingredient: 'SODIUM MYCOPHENOLATE',
      drugClass: '免疫抑制劑（mycophenolate 類，抑制 IMPDH／淋巴球增生）',
      license: '衛署藥輸字第023737號',
      indication: '1. 併用以cyclosporin的微乳劑型 (Microemulsion) 和皮質固醇以預防腎臟移植病人之急性排斥現象發生。2. 適用於在患有WHO第III、IV或第V類狼瘡性腎炎 (Lupusnephritis, LN) 的成人病人中作為前導與維持治療。此一適應症乃依據狼瘡性腎炎病人治療試驗的文獻報告，其中大多數病人屬於ISN/RPS（2003年）第IV類疾病。療效佐證是以替代指標為基準。',
      photoAsset: 'assets/drugs/lupus_mmf.jpg',
      fdaImage: false,
    ),
    DrugFull(
      slug: 'lupus_cyclophosphamide', disease: '紅斑性狼瘡',
      chiName: '癌得星注射劑',
      enName: 'Endoxan Injection',
      ingredient: 'CYCLOPHOSPHAMIDE MONOHYDRATE / CYCLOPHOSPHAMIDE MONOHYDRATE / CYCLOPHOSPHAMIDE MONOHYDRATE',
      drugClass: '烷化劑類化學治療藥（alkylating agent），亦作為免疫抑制劑用於自體免疫疾病',
      license: '衛署藥輸字第021304號',
      indication: '淋巴性白血病、散發性腫瘤、慢性淋巴性白血病、骨髓性淋巴病、淋巴肉芽腫及各種網狀組織細胞增多症、防止腫瘤復發。',
      photoAsset: 'assets/drugs/lupus_cyclophosphamide.jpg',
      fdaImage: false,
    ),
  ]),
  DiseaseGroup('肝癌', [
    DrugFull(
      slug: 'liver_sorafenib', disease: '肝癌',
      chiName: '索拿癌膜衣錠200毫克',
      enName: 'Sorafenib Sandoz Film-coated Tablets 200mg',
      ingredient: 'SORAFENIB TOSYLATE',
      drugClass: '口服標靶藥（multikinase inhibitor 多重激酶抑制劑）',
      license: '衛部藥輸字第028614號',
      appearanceMark: '紅色圓形，標記：200（紅棕色）',
      appearanceSource: '食藥署',
      indication: '轉移性或無法手術切除且不適合局部治療或局部治療失敗之晚期肝細胞癌(HCC)。 晚期腎細胞癌(RCC)且已接受interferon-alpha或interleukin-2治療失敗，或不適合以上兩種藥物治療之病患。 放射性碘治療無效之局部晚期或轉移性的進行性(progressive)分化型甲狀腺癌(DTC)。',
      photoAsset: 'assets/drugs/liver_sorafenib.jpg',
      fdaImage: true,
    ),
    DrugFull(
      slug: 'liver_sorafenib2', disease: '肝癌',
      chiName: '蕾莎瓦膜衣錠 200 毫克',
      enName: 'Nexavar film-coated tablets 200mg',
      ingredient: 'SORAFENIB TOSYLATE, MICRONIZED',
      drugClass: '口服標靶（多重激酶抑制劑 / oral multikinase inhibitor）',
      license: '衛署藥輸字第024727號',
      indication: '轉移性或無法手術切除且不適合局部治療或局部治療失敗之晚期肝細胞癌(HCC)。晚期腎細胞癌(RCC)且已接受interferon-alpha或interleukin-2治療失敗，或不適合以上兩種藥物治療之病患。放射性碘治療無效之局部晚期或轉移性的進行性(progressive)分化型甲狀腺癌(DTC)。',
      photoAsset: 'assets/drugs/liver_sorafenib2.jpg',
      fdaImage: false,
    ),
    DrugFull(
      slug: 'liver_lenvatinib', disease: '肝癌',
      chiName: '樂衛瑪膠囊4毫克',
      enName: 'Lenvima Capsules 4 mg',
      ingredient: 'Lenvatinib mesilate',
      drugClass: '口服標靶藥（多重受體酪胺酸激酶抑制劑 / 抗血管新生）',
      license: '衛部藥輸字第026933號',
      indication: '1.分化型甲狀腺癌(Differentiated thyroid cancer, DTC)：適用於放射性碘治療無效之進行性，且為局部晚期或轉移性之分化型甲狀腺癌之成人病人。2.腎細胞癌(Renal Cell Carcinoma, RCC)：與pembrolizumab併用，做為晚期腎細胞癌病人的第一線治療藥物。與everolimus併用，做為曾經接受過一種抗血管新生療法的晚期腎細胞癌病人的治療藥物。3.肝細胞癌(Hepatocellular Carcinoma)：適用於無法手術切除且不適合局部治療之晚期肝細胞癌病人。4.子宮內膜癌(Endometrial Carcinoma, EC)：與pembrolizumab併用適用於曾經以任何形式接受過全身性治療後疾病惡化，且不適合根治手術或放射治療之晚期子宮內膜癌病人。',
      dosage: '1.隨餐或空腹口服使用，須於每日同一時間服用。2.應整粒吞服或將膠囊先溶解於小杯液體後服用。',
      sideEffects: '疲倦(44-73%)、高血壓(42-73%)。',
      precautions: '1.將膠囊先溶解於小杯液體後服用：量取一大湯匙的水或蘋果汁於玻璃杯中後放入膠囊（膠囊不需打開或壓碎），靜置於液體中至少10分鐘，攪拌至少3分鐘後飲用液體；飲用後再加入等量（一大湯匙）的水或蘋果汁混勻後飲用完剩餘液體。2.有生育能力的婦女於本品治療期間及服用最後一個劑量後至少30天應採取有效之避孕措施。3.使用本品治療期間及服用最後一個劑量後至少1周需停止哺乳。存放：30℃以下儲存。忘記服藥：如未能在12小時內服用，應略過該次劑量並於原定服藥時間投予下一次劑量。',
      deepSource: 'druginfo.cmuh.org.tw',
      photoAsset: 'assets/drugs/liver_lenvatinib.jpg',
      fdaImage: false,
    ),
    DrugFull(
      slug: 'liver_regorafenib', disease: '肝癌',
      chiName: '癌瑞格膜衣錠40毫克',
      enName: 'Stivarga Film-Coated Tablets 40mg',
      ingredient: 'Regorafenib',
      drugClass: '口服標靶藥（multi-kinase inhibitor 多重激酶抑制劑）',
      license: '衛部藥輸字第026168號',
      indication: '大腸直腸癌：Regorafenib適用於治療先前曾接受下列療法的轉移性大腸直腸癌(mCRC)患者，療法包括fluoropyrimidine-、oxaliplatin-、irinotecan-為基礎的化療，和抗血管內皮生長因子((anti-VEGF)等療法；若KRAS為原生型(wild type)，則需接受過抗表皮生長因子受體(anti-EGFR)療法。腸胃道間質腫瘤：適用於治療先前曾接受imatinib mesylate和sunitinib malate患者之局部晚期、無法切除或轉移性的胃腸道間質瘤。肝細胞癌：適用於治療曾接受sorafenib治療的肝細胞癌(HCC)病患。',
      photoAsset: 'assets/drugs/liver_regorafenib.jpg',
      fdaImage: false,
    ),
    DrugFull(
      slug: 'liver_bevacizumab', disease: '肝癌',
      chiName: '癌思停 注射劑',
      enName: 'AVASTIN INJECTION',
      ingredient: 'BEVACIZUMAB',
      drugClass: '標靶藥（抗血管新生／VEGF 血管內皮細胞生長因子抑制劑，單株抗體）',
      license: '衛署菌疫輸字第000807號',
      indication: '1. 轉移性大腸直腸癌 (mCRC)：Avastin (bevacizumab) 與含有5-fluorouracil為基礎的化學療法合併使用，可以作為轉移性大腸或直腸癌病人的第一線治療。Avastin與含有5-fluorouracil/leucovorin/oxaliplatin的化學療法合併使用，可以作為先前接受過以fluoropyrimidine為基礎的化學療法無效且未曾接受過Avastin治療的轉移性大腸或直腸癌病人的治療。Avastin (bevacizumab) 與含有fluoropyrimidine-irinotecan-或fluoropyrimidine-oxaliplatin-為基礎的化學療法合併使用，可以做為第一線已接受過以Avastin併用化療後惡化之轉移性大腸或直腸癌病人的第二線治療。2. 轉移性乳癌 (mBC)：Avastin與paclitaxel合併使用，可以做為HER2 (-) 轉移性乳癌病人的第一線治療。3. 惡性神經膠質瘤（WHO第4級）-神經膠母細胞瘤：Avastin單獨使用可用於治療曾接受標準放射線治療且含temozolomide在內之化學藥物治療失敗之多型性神經膠母細胞瘤 (Glioblastoma multiforme) 復發之成人病人。4. 晚期、轉移性或復發性非鱗狀非小細胞肺癌 (NSCLC)：Avastin與carboplatin及paclitaxel合併使用，可以作為無法切除的晚期、轉移性或復發性非鱗狀非小細胞肺癌病人的第一線治療。Avastin併用erlotinib，可作為無法手術切除的晚期、轉移性或復發性且帶有表皮生長因子受體 (EGFR) 活化性突變的非鱗狀非小細胞肺癌病人的第一線治療。5. 卵巢上皮細胞、輸卵管或原發性腹膜癌 (Epithelial Ovarian, Fallopian Tube or Primary Peritoneal Cancer)：Avastin與carboplatin及paclitaxel合併使用，接著單獨使用Avastin，可以做為第三期或第四期卵巢上皮細胞、輸卵管或原發性腹膜癌病人接受初次手術切除後之治療。Avastin與carboplatin及gemcitabine合併使用，可以做為曾接受過第一線含鉑類藥物 (platinum-based) 化學治療間隔至少6個月再復發（即，對含鉑藥物具感受性），且未曾接受過bevacizumab或其他血管內皮細胞生長因子 (VEGF) 抑制劑或血管內皮細胞生長因子接受器之標靶藥物 (VEGF receptor-targeted agents) 治療之復發性卵巢上皮細胞、輸卵管或原發性腹膜癌病人的治療。Avastin與carboplatin及paclitaxel合併使用，接著單獨使用Avastin治療，可以做為對含鉑藥物具感受性之復發性卵巢上皮細胞、輸卵管或原發性腹膜癌病人的治療。Avastin併用paclitaxel、topotecan或pegylated liposomal doxorubicin可以做為接受過含鉑類藥物 (platinum-based) 化療治療後6個月內再復發（即，對含鉑藥物具抗藥性）、之前接受不超過2種化療療程且未曾接受過bevacizumab或其他血管內皮細胞生長因子 (VEGF) 抑制劑或血管內皮細胞生長因子接受器之標靶藥物 (VEGF receptor-targeted agents) 之復發性卵巢上皮細胞、輸卵管或原發性腹膜癌病人的治療。6. 持續性、復發性或轉移性之子宮頸癌 (Persistent, Recurrent, or Metastatic Cervical Cancer)：Avastin與paclitaxel及cisplatin合併使用可用於治療持續性、復發性或轉移性之子宮頸癌。Avastin與paclitaxel及topotecan合併使用可用於無法接受含鉑類藥物治療 (platinum therapy) 病人之持續性、復發性或轉移性子宮頸癌。',
      photoAsset: 'assets/drugs/liver_bevacizumab.jpg',
      fdaImage: true,
    ),
    DrugFull(
      slug: 'liver_nivolumab', disease: '肝癌',
      chiName: '保疾伏',
      enName: 'OPDIVO (nivolumab) Injection 10mg/mL',
      ingredient: 'Nivolumab',
      drugClass: '免疫檢查點抑制劑（抗 PD-1 單株抗體，免疫腫瘤治療）',
      license: '衛部菌疫輸字第001013號',
      indication: '適應症：１、無法切除或轉移性黑色素瘤：單一療法或併用ipilimumab適用於治療無法切除或轉移性黑色素瘤病人。 ２、黑色素瘤之輔助治療：適用於黑色素瘤侵犯至淋巴結或已轉移且曾進行完全切除性手術之病人的輔助治療。 ３、可切除之非小細胞肺癌的術前輔助治療：併用含鉑化學治療適用於可切除（腫瘤≧4公分或淋巴結陽性）且不具EGFR或ALK腫瘤基因異常之非小細胞肺癌(NSCLC)成年病人的術前輔助治療。 ４、非小細胞肺癌：(1)併用ipilimumab適用於帶有PD-L1 (≧1%)且不具EGFR或ALK腫瘤基因異常的轉移性或復發性非小細胞肺癌(NSCLC)成年病人的第一線治療。(2)併用ipilimumab及2個週期含鉑化學治療適用於不具EGFR或ALK腫瘤基因異常的轉移性或復發性非小細胞肺癌(NSCLC)成年病人的第一線治療。(3)併用 carboplatin、paclitaxel及 bevacizumab適用於不具EGFR或 ALK腫瘤基因異常的轉移性或復發性非鱗狀非小細胞肺癌(non-squamous NSCLC) 成年病人的第一線治療。(4)適用於接受含鉑化學治療時或之後疾病惡化的晚期非小細胞肺癌(NSCLC)病人，病人若具有EGFR或ALK腫瘤基因異常者，則須經EGFR或ALK抑制劑治療後出現疾病惡化現象。 ５、惡性肋膜間皮瘤：併用ipilimumab適用於無法切除之惡性肋膜間皮瘤成人病人的第一線治療。 ６、腎細胞癌：(1)適用於先前經抗血管新生療法治療(anti-angiogenic therapy)的晚期腎細胞癌病人。(2)併用ipilimumab可用於治療中度/重度風險(intermediate/poor-risk)先前未曾接受治療的晚期腎細胞癌病人。(3)併用cabozantinib適用於未曾接受治療的晚期腎細胞癌病人。 ７、頭頸部鱗狀細胞癌：適用於接受含鉑化學治療時或之後疾病惡化的復發或轉移性頭頸部鱗狀細胞癌(SCCHN)病人。 ８、典型何杰金氏淋巴瘤：適用於經下列方式治療後復發或惡化的典型何杰金氏淋巴瘤成人病人：(1)接受自體造血幹細胞移植(HSCT)與brentuximab vedotin，或(2)接受3種或3種以上全身性療法，包括自體造血幹細胞移植(HSCT)。 本項適應症係依據客觀反應率(objective response rate)獲得加速核准。適應症的持續核准須要後續確認性試驗(confirmatory trial)證明確實達到臨床效益。 ９、泌尿道上皮癌：(1)併用cisplatin和gemcitabine適用於無法切除或轉移性泌尿道上皮癌成人病人的第一線治療。(2)適用於治療接受含鉑療法期間或之後惡化的局部晚期無法切除或轉移性泌尿道上皮癌病人。本項適應症係依據腫瘤反應率(tumor response rate)及治療反應持續時間(duration of response)獲得加速核准。適應症的持續核准須要後續確認性試驗(confirmatory trial)證明確實達到臨床效益。(3)適用於在接受根治性切除術後，有高度復發風險的泌尿道上皮癌病人輔助治療。 １０、胃癌、胃食道癌或食道腺癌：(1)併用fluoropyrimidine及含鉑化學治療適用於治療晚期或轉移性，且不具有HER2過度表現的胃癌或胃食道癌(Gastroesophageal Junction, GEJ)或食道腺癌的病人。(2)適用於治療先前經兩種或兩種以上化學治療的晚期或復發性胃癌或胃食道癌的病人。 １１、肝細胞癌：併用ipilimumab適用於治療先前曾接受sorafenib 治療的肝細胞癌(HCC)病人。 １２、轉移性大腸直腸癌：單一藥物或併用ipilimumab適用於接受fluoropyrimidine、oxaliplatin和irinotecan治療後疾病惡化之具有高度微衛星不穩定性(MSI-H)或錯誤配對修復缺陷(dMMR)的轉移性大腸直腸癌(CRC)成人病人。本適應症係依據客觀反應率獲得加速核准，此適應症仍須執行確認性試驗以證明其臨床效益。 １３、食道鱗狀細胞癌：(1)併用含fluoropyrimidine及含鉑的化學治療適用於晚期或轉移性食道鱗狀細胞癌(ESCC)病人的第一線治療。(2)併用ipilimumab適用於晚期或轉移性食道鱗狀細胞癌(ESCC)病人的第一線治療。(3)適用於曾接受合併含鉑及fluoropyrimidine 化學治療之後惡化的無法切除晚期或復發性食道鱗狀細胞癌(esophageal squamous cell carcinoma)病人。 １４、食道癌或胃食道癌切除的輔助治療：適用於曾接受術前同步化學與放射治療(neoadjuvant concurrent chemoradiotherapy)與手',
      photoAsset: 'assets/drugs/liver_nivolumab.jpg',
      fdaImage: false,
    ),
  ]),
  DiseaseGroup('高血壓及併發心臟疾病', [
    DrugFull(
      slug: 'htn_amlodipine', disease: '高血壓及併發心臟疾病',
      chiName: '舒脈優膜衣錠 20/5/12.5毫克',
      enName: 'Sevikar HCT 20/5/12.5mg',
      ingredient: 'AMLODIPINE BESYLATE / HYDROCHLOROTHIAZIDE (EQ TO 3,4-DIHYDROCHLOROTHIAZIDE) / OLMESARTAN MEDOXOMIL',
      drugClass: 'CCB（鈣離子通道阻斷劑，dihydropyridine 類）',
      license: '衛署藥輸字第025492號',
      indication: '治療高血壓。本品適用於以Olmesartan、Amlodipine、Hydrochlorothiazide其中兩種成分合併治療，仍無法有效控制血壓的高血壓病患。',
      photoAsset: 'assets/drugs/htn_amlodipine.jpg',
      fdaImage: true,
    ),
    DrugFull(
      slug: 'htn_olmesartan', disease: '高血壓及併發心臟疾病',
      chiName: '可悅您膜衣錠50毫克',
      enName: 'COZAAR F.C. TABLETS 50MG',
      ingredient: 'LOSARTAN POTASSIUM',
      drugClass: 'ARB（血管收縮素II受體拮抗劑）',
      license: '衛署藥輸字第021914號',
      indication: '高血壓，治療第II型糖尿病腎病變。',
      photoAsset: 'assets/drugs/htn_olmesartan.jpg',
      fdaImage: true,
    ),
    DrugFull(
      slug: 'htn_valsartan', disease: '高血壓及併發心臟疾病',
      chiName: '可得安穩 80/12.5 毫克膜衣錠',
      enName: 'Co-Diovan 80/12.5 mg Film Coated Tablets',
      ingredient: 'VALSARTAN / HYDROCHLOROTHIAZIDE (EQ TO 3,4-DIHYDROCHLOROTHIAZIDE)',
      drugClass: 'ARB（血管收縮素受體拮抗劑）+ Thiazide 利尿劑 複方降壓藥',
      license: '衛署藥輸字第023109號',
      indication: '單一療法無法控制的高血壓，做為第二線用藥。',
      dosage: '飯後服用（請依藥袋指示服用）。忘記服藥時：想起時立即服用；若已接近下一次服藥時間，則只需服用下一次劑量，不可同時服用雙倍藥量。',
      sideEffects: '頭痛、眩暈、疲勞、咳嗽',
      precautions: '1.用藥期間應監測水份及電解質，遇大量流汗、腹瀉或嘔吐等情況，易造成脫水危險，如有心跳不規則、異常口乾等症狀，應儘速就醫。2.可能升高血糖值，糖尿病患者應規律監測血糖。3.皮膚對日光較敏感，避免過度曝曬日光。4.可能產生眩暈，請避免開車或操作機械等具危險性工作。5.突然停藥會導致病情惡化，請遵醫囑服藥。',
      contraindication: '高血壓且懷孕之婦女不建議使用本藥。',
      deepSource: 'druginfo.cmuh.org.tw',
      photoAsset: 'assets/drugs/htn_valsartan.jpg',
      fdaImage: false,
    ),
    DrugFull(
      slug: 'htn_bisoprolol', disease: '高血壓及併發心臟疾病',
      chiName: '康肯5毫克',
      enName: 'CONCOR 5',
      ingredient: 'BISOPROLOL FUMARATE',
      drugClass: '乙型阻斷劑（Beta-blocker，β1 選擇性；治療高血壓、狹心症與慢性心衰竭）',
      license: '衛署藥輸字第017125號',
      indication: '高血壓，狹心症，穩定型慢性中度至重度（NYHA class III、IV）心衰竭。',
      photoAsset: 'assets/drugs/htn_bisoprolol.jpg',
      fdaImage: false,
    ),
    DrugFull(
      slug: 'htn_clopidogrel', disease: '高血壓及併發心臟疾病',
      chiName: '保栓通膜衣錠75毫克',
      enName: 'PLAVIX FILM-COATED TABLETS 75MG',
      ingredient: 'CLOPIDOGREL HYDROGEN SULFATE',
      drugClass: '抗血小板藥（P2Y12 ADP 受體拮抗劑）',
      license: '衛署藥輸字第022932號',
      appearanceMark: '粉色圓形，標記：75（8mm）',
      appearanceSource: '食藥署',
      indication: '１、降低近期發生中風、心肌梗塞或周邊動脈血管疾病的粥狀動脈硬化病人之粥狀動脈栓塞事件(如：心肌梗塞、中風或其他因血管病變引起的死亡)的發生。２、與aspirin併用降低非ST段上升之急性冠心症(不穩定性心絞痛和非Q波型心肌梗塞)病人(包括經皮冠狀動脈介入性治療後放置支架的病人)之粥狀動脈栓塞事件。３、與aspirin併用可用於以內科治療的ST段上升之急性心肌梗塞病人。４、不適合接受Vitamin K antagonists的心房纖維顫動病人，併有至少一個發生血管事件危險因子，且屬於出血危險性低者，可與aspirin併用以預防粥狀動脈栓塞及血栓栓塞事件，包括中風。５、與Aspirin併用，適用於降低急性缺血性腦中風(NIHSS分數≤3)或中度至高度風險暫時性腦缺血(TIA)病人之中風風險。',
      photoAsset: 'assets/drugs/htn_clopidogrel.jpg',
      fdaImage: true,
    ),
    DrugFull(
      slug: 'htn_aspirin', disease: '高血壓及併發心臟疾病',
      chiName: '伯基腸溶微粒膠囊100毫克(乙醯水楊酸)',
      enName: 'BOKEY ENTERIC-MICROENCAPSULATED CAPSULES 100MG(ASPIRIN)',
      ingredient: 'ASPIRIN / ASPIRIN / ASPIRIN',
      drugClass: '抗血小板',
      license: '衛署藥製字第037344號',
      indication: '預防心肌梗塞，預防血栓性栓塞症，短暫性缺血性發作',
      photoAsset: 'assets/drugs/htn_aspirin.jpg',
      fdaImage: false,
    ),
  ]),
];
